
tabItemsUI <- tabItems(
  tabItem(tabName = "worldMap",
          fluidRow(
            width = "100%",
            box(
              style = "max-height: 83vh; overflow-y: hidden;",
              width = "100%",
              addSpinner(leafletOutput("map", width = "100%", height="82vh"), "dots", "dark grey"))),
          fluidRow(width = "100%", align = "center", 
                   div(style="display:inline-block;",textInput(inputId="latInPred", 
                                                               label="Latitude", value = 37.2284)),
                   div(style="display:inline-block;",textInput(inputId="longInPred", 
                                                               label="Longitude", value = -80.4249983)),
                   div(style="display:inline-block;",actionButton("predButton", "Predict")),
                   div(style="display:inline-block;",textOutput("probText"))
          )
  ),
  tabItem(tabName="featureImportance", 
          fluidRow(width="100%",
                   box(width="100%",
                       addSpinner(plotOutput("importance", height="550px"), "dots", color = "dark grey"))),
          fluidRow(width="50%", align="center", div(style = "height:14px; font-size:18px; width:1000px; font-family:Crimson Text",
                                                    "This visual is showing feature importance through the Gain statistic. The Gain is the average
                   training loss reduction gained when using a particular feature for splitting. View the 'Modeling' tab for more information on Gain."))),
  
  tabItem(tabName="shapImpact", 
          fluidRow(width="100%",
                   box(width="100%",
                       addSpinner(plotOutput("shap", height="550px"), "dots", color = "dark grey"))),
          fluidRow(width="50%", align="center", div(style = "height:14px; font-size:18px; width:1000px; font-family:Crimson Text",
                                                    "Each dot represents a Longitude/Latitude pair. The x-axis represents the impact of the feature on the model's
                   prediction (via Log-Odds). The color of the dot represents the value of the feature's data point. Note, most prominent features are sorted from top to bottom. View the 'Modeling'
                   tab for more information on Shapley Values."))),
  
  tabItem(tabName="refs", 
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; font-family:Crimson Text",
                                                    "Modeling")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:14x; font-size:18px; width:1000px; font-family:Crimson Text",
                                                    "The Tree of Heaven (Ailanthus altissima) was modeled with Extreme Gradient Boosted Classification Trees. In order to train the model, both presence and absence data was required.
                                                    Pseudo Absence Points were randomly generated with the current distribution of the Tree of Heaven througout the United States.
                                                    In training the model, a 70-30% split was used with random stratified sampling. 10 cross fold validation was performed for the tuning of the hyperparameters to avoid
                                                    overfitting the data. The data points on the geographical maps are sampled from a geoJSON file (~100,000 evenly space points). The maps shows the probability of a Tree of Heaven occurence at a specific Longitude and Latitude.")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    "Gain")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:14x; font-size:18px; width:1000px; font-family:Crimson Text",
                                                    "Information Gain (Gain) is the reduction in entropy by transforming a dataset. In other words, it measures the reduction in entropy by splitting a dataset according to a given value of a random variable. It is calculated by comparing the entropy of the dataset before and after a transformation (Jason Brownlee, 2019).")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    "Shapley Values")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:14x; font-size:18px; width:1000px; font-family:Crimson Text",
                                                    "Shapley values were originally implemented as a method in coalitional game theory (i.e how do we fairly distribute payout amoung different features?).
                                                    The payout is based upon the feature's contribution to the total payout. The Shapley value is the average marginal contribution of a feature value across all possible coalitions (Christoph Molnar, 2020). 
                                                    For a more detailed explanation on Shapley Values visit https://christophm.github.io/interpretable-ml-book/shapley.html#general-idea.")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:10px; font-size:12px; font-family:Crimson Text",
                                                    "Brownlee, Jason. Information Gain and Mutual Information for Machine Learning. Machine Learning Mastery, 27 Aug. 2020, machinelearningmastery.com/information-gain-and-mutual-information/.")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:10px; font-size:12px; font-family:Crimson Text",
                                                    "Molnar, Christoph. Interpretable Machine Learning. Christoph Molnar, 23 Nov. 2020, christophm.github.io/interpretable-ml-book/index.html."))),
  
  tabItem(tabName = "aboutSpecies",
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; font-family:Crimson Text",
                                                    "About the Species")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(column(12, align="center",
                          div(style="display: inline-block;",img(src="fullTree.jpg", height=320, width=240)),
                          div(style="display: inline-block;",img(src="treeSeeds.jpg", height=240, width=320)),
                          div(style="display: inline-block;",img(src="bark.jpg", height=320, width=240)))),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:14x; font-size:18px; width:1000px; font-family:Crimson Text",
                                                    "Our capstone team was tasked with identifying an extremely invasive species in Virginia and modeling its potential spread. We identified the species Ailanthus altissima, 'Tree of Heaven',  as one of the most invasive plant species in Virginia to model. Currently, there are more than 1600 reported sightings of the tree in just Virginia, with over 24,000 sightings in the continental United States. A map of user-reported occurrences can be viewed at ", a("eddMaps.", href = "https://www.eddmaps.org/distribution/viewmap.cfm?sub=3003"), " The Tree of Heaven originated from China in the late 1700s. This plant is the fastest-growing tree in North America, growing up to 80 feet tall. It is considered invasive because of its aggressive growth and its ability to kill surrounding native plants through a toxin found in its bark, stems, and leaves. The tree is also able to produce high volumes of seeds rapidly, and it can survive in a wide variety of climates. The tree's roots are known to cause extensive structural damage, and the tree's toxicity poses a threat to the balance in native ecosystems.")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:10px; font-size:12px; font-family:Crimson Text",
                                                    "Tree-of-Heaven. Tree-of-Heaven | National Invasive Species Information Center, www.invasivespeciesinfo.gov/terrestrial/plants/tree-heaven. ")),
          fluidRow(width="50%", align="center", div(style = "height:10px; font-size:12px; font-family:Crimson Text",
                                                    "Leftmost image source: CC BY-SA 2.1 es, https://commons.wikimedia.org/w/index.php?curid=139593")),
          fluidRow(width="50%", align="center", div(style = "height:10px; font-size:12px; font-family:Crimson Text",
                                                    "Rightmost image source: By Kurt Stuber - caliban.mpiz-koeln.mpg.de/mavica/index.html part of www.biolib.de, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=3340"))
  ),
  
  tabItem(tabName="references", 
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family:Crimson Text",
                                                    "Contacts")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family:Crimson Text",
                                                    "Team ACE: Akshay Patel (akshayjp@vt.edu), Colton Mumley (colton12@vt.edu), Evan Mitchell (evanmitchell@vt.edu)")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family: Crimson Text",
                                                    "Sponsors: Dr. Alexandra Hanlon (alhanlon@vt.edu) and Jennifer West (jenni75@vt.edu)")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family: Crimson Text",
                                                    "Project")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family:Crimson Text",
                                                    "Our Computational Modeling and Data Analytics Capstone Project (CMDA at Virginia Tech) was sponsored by the Center
                                                    for Biostatistics and Health Data Science (CBHDS). Team ACE was tasked with developing a
                                                    model and application to help researchers/engineers plan for an invasive species similar to the Tree of Heaven.")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family:Crimson Text",
                                                    "Info about the Team")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family:Crimson Text",
                                                    "Akshay Patel, Colton Mumley, Evan Mitchell: VT CMDA Majors graduating in May 2021")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px; width:1000px;font-family:Crimson Text",
                                                    "Dr. Alexandra Hanlon: Director for CBHDS, Jennifer West: Research Associate for CBHDS")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(width="50%", align="center", div(style = "height:16px; font-size:20px;",
                                                    " ")),
          fluidRow(column(12, align="center",
                          div(style="display: inline-block;",img(src="cmdaLogo.jpg", height=200, width=200)),
                          div(style="display: inline-block;",img(src="CBHDS_logo.jpg", height=100, width=180))))),
  
  tabItem(tabName = "alabama",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",
                       addSpinner(leafletOutput("alabama", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "arkansas",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("arkansas", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "arizona",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("arizona", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "california",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("california", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "colorado",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("colorado", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "connecticut",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("connecticut", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "delaware",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("delaware", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "florida",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("florida", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "georgia",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("georgia", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "iowa",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("iowa", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "idaho",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("idaho", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "illinois",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("illinois", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "indiana",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("indiana", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "kansas",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("kansas", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "kentucky",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("kentucky", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "louisiana",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%", 
                       addSpinner(leafletOutput("louisiana", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "massachusetts",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("massachusetts", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "maryland",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("maryland", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "maine",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("maine", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "michigan",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("michigan", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "minnesota",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("minnesota", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "missouri",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("missouri", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "mississippi",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("mississippi", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "montana",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("montana", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "north_carolina",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("north_carolina", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "north_dakota",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("north_dakota", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "nebraska",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("nebraska", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "new_hampshire",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("new_hampshire", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "new_jersey",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("new_jersey", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "new_mexico",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("new_mexico", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "nevada",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("nevada", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "new_york",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("new_york", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "ohio",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("ohio", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "oklahoma",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("oklahoma", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "oregon",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("oregon", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "pennsylvania",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("pennsylvania", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "rhode_island",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("rhode_island", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "south_carolina",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("south_carolina", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "south_dakota",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("south_dakota", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "tennessee",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("tennessee", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "texas",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("texas", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "utah",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("utah", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "virginia",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("virginia", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "vermont",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("vermont", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "washington",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("washington", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "wisconsin",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("wisconsin", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "west_virginia",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("west_virginia", width="100%", height="90vh"), "dots", "dark grey")))),
  
  tabItem(tabName = "wyoming",
          fluidRow(width="12",
                   box(style = "max-height: 91vh; overflow-y: hidden", width="100%",  addSpinner(leafletOutput("wyoming", width="100%", height="90vh"), "dots", "dark grey"))))
  
)
